sudo: required
language: node_js

services:
  - docker

node_js:
  - "6.9"

env:
  DOCKER_COMPOSE_VERSION: 1.11.2

before_install:
  # updated and install the latest docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  # remove and install specific docker-compose version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  # do a version check
  - docker version
  - docker-compose version
  - npm test
notifications:
  email:
    recipients:
      # add your email here for CI updates.
