sudo: required
language: node_js

services:
  - docker

node_js:
  - "6.9"

script:
  - docker version
  - docker-compose version
  - npm test
notifications:
  email:
    recipients:
      # add your email here for CI updates.
